use super::*;

#[allow(clippy::too_many_arguments)]
pub fn attention_block_window_for_layer(
    runtime: &mut Runtime,
    layer_idx: usize,
    normed_input: &[f32],
    q_cols: usize,
    q_raw: &[u8],
    q_dim: usize,
    q_quant: Quant,
    k_raw: &[u8],
    kv_dim: usize,
    k_quant: Quant,
    v_raw: &[u8],
    v_rows: usize,
    v_quant: Quant,
    pos_start: usize,
    num_heads: usize,
    num_kv_heads: usize,
    head_dim: usize,
    o_raw: &[u8],
    hidden_dim: usize,
    o_cols: usize,
    o_quant: Quant,
    residual_input: &[f32],
    ffn_norm_data: &[f32],
    norm_eps: f32,
    gate_raw: &[u8],
    gate_rows: usize,
    gate_cols: usize,
    gate_quant: Quant,
    up_raw: &[u8],
    up_rows: usize,
    up_cols: usize,
    up_quant: Quant,
    down_raw: &[u8],
    down_rows: usize,
    down_cols: usize,
    down_quant: Quant,
    hidden_after_window: &mut [f32],
) -> Result<(), String> {
    runtime.attention_block_window_for_layer(
        layer_idx as u16,
        normed_input,
        q_cols,
        q_raw,
        q_dim,
        q_quant,
        k_raw,
        kv_dim,
        k_quant,
        v_raw,
        v_rows,
        v_quant,
        pos_start,
        num_heads,
        num_kv_heads,
        head_dim,
        o_raw,
        hidden_dim,
        o_cols,
        o_quant,
        residual_input,
        ffn_norm_data,
        norm_eps,
        ffn_gate_id(layer_idx),
        gate_raw,
        gate_rows,
        gate_cols,
        gate_quant,
        ffn_up_id(layer_idx),
        up_raw,
        up_rows,
        up_cols,
        up_quant,
        ffn_down_id(layer_idx),
        down_raw,
        down_rows,
        down_cols,
        down_quant,
        hidden_after_window,
    )
}

#[allow(clippy::too_many_arguments)]
pub fn o_proj_gemv_window(
    runtime: &mut Runtime,
    layer_idx: usize,
    raw: &[u8],
    rows: usize,
    cols: usize,
    quant: Quant,
    input: &[f32],
    output: &mut [f32],
) -> Result<(), String> {
    runtime.gemv_window(
        backend_o_proj_id(layer_idx),
        raw,
        rows,
        cols,
        quant,
        input,
        output,
    )
}

#[allow(clippy::too_many_arguments)]
pub fn ffn_chain_window_with_residual_from_resident_input(
    runtime: &mut Runtime,
    layer_idx: usize,
    hidden_all: &mut [f32],
    hidden_dim: usize,
    residual_input: &[f32],
    norm_weight: &[f32],
    norm_eps: f32,
    gate_raw: &[u8],
    gate_rows: usize,
    gate_cols: usize,
    gate_quant: Quant,
    up_raw: &[u8],
    up_rows: usize,
    up_cols: usize,
    up_quant: Quant,
    down_raw: &[u8],
    down_rows: usize,
    down_cols: usize,
    down_quant: Quant,
) -> Result<(), String> {
    runtime.ffn_chain_window_with_residual_from_resident_input(
        hidden_all,
        hidden_dim,
        residual_input,
        norm_weight,
        norm_eps,
        ffn_gate_id(layer_idx),
        gate_raw,
        gate_rows,
        gate_cols,
        gate_quant,
        ffn_up_id(layer_idx),
        up_raw,
        up_rows,
        up_cols,
        up_quant,
        ffn_down_id(layer_idx),
        down_raw,
        down_rows,
        down_cols,
        down_quant,
    )
}
